# Generated By: Claude Code (Claude Opus 4.6)
# Makefile for github-velocity (flat script layout, no package directory)

.PHONY: check help install-dev clean format format-check lint typecheck test test-verbose coverage

SOURCE_DIR := velocity
SOURCE_FILES := $(SOURCE_DIR)/refresh.py
TEST_DIR := tests

ifeq ($(OS),Windows_NT)
    VENV_DIR ?= .venv
    PYTHON ?= $(VENV_DIR)/Scripts/python.exe
else
    VENV_DIR ?= .venv
    PYTHON ?= $(VENV_DIR)/bin/python
endif

$(info venv: $(VENV_DIR))

check: format lint typecheck test  ## Run format, lint, typecheck, test (default)

.DEFAULT_GOAL := check

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

$(PYTHON):
	python3 -m venv $(VENV_DIR)

install-dev: $(PYTHON)  ## Install dev dependencies
	$(PYTHON) -m pip install --quiet -e ".[dev]"

clean:  ## Remove build artifacts and caches
	rm -rf build/ dist/ *.egg-info .mypy_cache/ .pytest_cache/ htmlcov/
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true

format: install-dev  ## Format code with black
	$(PYTHON) -m black $(SOURCE_FILES)

format-check: install-dev  ## Check formatting without modifying files
	$(PYTHON) -m black --check $(SOURCE_FILES)

lint: install-dev  ## Lint with flake8
	$(PYTHON) -m flake8 --max-line-length=88 --extend-ignore=E203,W503 $(SOURCE_FILES)

typecheck: install-dev  ## Type check with mypy
	$(PYTHON) -m mypy $(SOURCE_FILES)

test: install-dev  ## Run pytest
	$(PYTHON) -m pytest || test $$? -eq 5

test-verbose: install-dev  ## Run pytest with verbose output
	$(PYTHON) -m pytest -v

coverage: install-dev  ## Run pytest with coverage (80% threshold)
	$(PYTHON) -m pytest --cov=. --cov-include=$(SOURCE_FILES) --cov-report=term --cov-fail-under=80
