# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for velocity/refresh.py compact functions and metric extractors."""

from velocity.refresh import (
    compact_closed,
    compact_merged,
    compact_open,
    count_main_merges,
    extract_reviewers,
)


# --- count_main_merges ---


def test_count_main_merges_no_commits():
    assert count_main_merges({}) == 0
    assert count_main_merges({"commits": []}) == 0


def test_count_main_merges_no_merges():
    pr = {
        "commits": [
            {"messageHeadline": "feat: add widget"},
            {"messageHeadline": "fix tests"},
        ]
    }
    assert count_main_merges(pr) == 0


def test_count_main_merges_merge_branch_main():
    pr = {
        "commits": [
            {"messageHeadline": "feat: add widget"},
            {
                "messageHeadline": (
                    "Merge branch 'main' into feature/widget"
                )
            },
            {"messageHeadline": "fix tests"},
            {
                "messageHeadline": (
                    "Merge branch 'main' into feature/widget"
                )
            },
        ]
    }
    assert count_main_merges(pr) == 2


def test_count_main_merges_remote_tracking():
    pr = {
        "commits": [
            {
                "messageHeadline": (
                    "Merge remote-tracking branch"
                    " 'origin/main' into feature/x"
                )
            },
        ]
    }
    assert count_main_merges(pr) == 1


def test_count_main_merges_ignores_other_merges():
    pr = {
        "commits": [
            {
                "messageHeadline": (
                    "Merge branch 'feature/other'"
                    " into feature/widget"
                )
            },
            {"messageHeadline": "Merge pull request #42"},
        ]
    }
    assert count_main_merges(pr) == 0


# --- extract_reviewers ---


def test_extract_reviewers_empty():
    assert extract_reviewers({}) == []
    assert extract_reviewers({"reviews": []}) == []


def test_extract_reviewers_deduplicates_and_sorts():
    pr = {
        "reviews": [
            {"author": {"login": "carol"}, "state": "COMMENTED"},
            {"author": {"login": "alice"}, "state": "APPROVED"},
            {"author": {"login": "carol"}, "state": "APPROVED"},
        ]
    }
    assert extract_reviewers(pr) == ["alice", "carol"]


def test_extract_reviewers_skips_empty_login():
    pr = {
        "reviews": [
            {"author": {"login": ""}, "state": "COMMENTED"},
            {"author": {"login": "bob"}, "state": "APPROVED"},
            {"author": {}, "state": "APPROVED"},
        ]
    }
    assert extract_reviewers(pr) == ["bob"]


# --- compact_merged ---


def test_compact_merged_basic():
    pr = {
        "additions": 100,
        "deletions": 20,
        "author": {"is_bot": False, "login": "alice"},
        "baseRefName": "main",
        "createdAt": "2026-04-01T10:00:00Z",
        "mergedAt": "2026-04-02T14:00:00Z",
        "number": 42,
        "title": "feat: add widget",
        "commits": [],
        "reviews": [],
    }
    result = compact_merged(pr, "org/repo")
    assert result["repo"] == "org/repo"
    assert result["number"] == 42
    assert result["additions"] == 100
    assert result["deletions"] == 20
    assert result["author"]["login"] == "alice"
    assert result["mainMerges"] == 0
    assert result["reviewers"] == []
    assert result["title"] == "feat: add widget"


def test_compact_merged_truncates_title():
    pr = {
        "additions": 0,
        "deletions": 0,
        "author": {"is_bot": False, "login": "bob"},
        "baseRefName": "main",
        "createdAt": "2026-04-01T10:00:00Z",
        "mergedAt": "2026-04-02T14:00:00Z",
        "number": 1,
        "title": "x" * 100,
        "commits": [],
        "reviews": [],
    }
    result = compact_merged(pr, "org/repo")
    assert len(result["title"]) == 50


def test_compact_merged_with_metrics():
    pr = {
        "additions": 50,
        "deletions": 10,
        "author": {"is_bot": False, "login": "bob"},
        "baseRefName": "main",
        "createdAt": "2026-04-01T10:00:00Z",
        "mergedAt": "2026-04-03T14:00:00Z",
        "number": 99,
        "title": "fix: handle edge case",
        "commits": [
            {"messageHeadline": "fix: handle edge case"},
            {
                "messageHeadline": (
                    "Merge branch 'main' into fix/edge-case"
                )
            },
        ],
        "reviews": [
            {"author": {"login": "alice"}, "state": "APPROVED"},
            {
                "author": {"login": "carol"},
                "state": "CHANGES_REQUESTED",
            },
        ],
    }
    result = compact_merged(pr, "org/repo")
    assert result["mainMerges"] == 1
    assert result["reviewers"] == ["alice", "carol"]


# --- compact_open ---


def test_compact_open_basic():
    pr = {
        "number": 10,
        "title": "feat: new thing",
        "author": {"login": "dev"},
        "baseRefName": "main",
        "createdAt": "2026-04-05T10:00:00Z",
        "additions": 100,
        "deletions": 50,
        "isDraft": False,
    }
    result = compact_open(pr, "org/repo")
    assert result["r"] == "org/repo"
    assert result["n"] == 10
    assert result["a"] == "dev"
    assert result["l"] == 150
    assert result["d"] == 0


def test_compact_open_draft():
    pr = {
        "number": 11,
        "title": "wip: draft PR",
        "author": {"login": "dev"},
        "baseRefName": "main",
        "createdAt": "2026-04-05T10:00:00Z",
        "additions": 10,
        "deletions": 5,
        "isDraft": True,
    }
    result = compact_open(pr, "org/repo")
    assert result["d"] == 1


# --- compact_closed ---


def test_compact_closed_basic():
    pr = {
        "number": 20,
        "title": "superseded by #21",
        "author": {"login": "dev"},
        "createdAt": "2026-04-01T10:00:00Z",
        "closedAt": "2026-04-03T10:00:00Z",
        "additions": 200,
        "deletions": 100,
    }
    result = compact_closed(pr, "org/repo")
    assert result["r"] == "org/repo"
    assert result["n"] == 20
    assert result["a"] == "dev"
    assert result["l"] == 300
    assert result["x"] == "2026-04-03"
    assert result["c"] == "2026-04-01"
