#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Refresh velocity dashboard data from GitHub API.

Usage: python3 velocity/refresh.py --repo owner/repo [--repo owner/repo2] [--days 42]
Output: output/dashboard.html

Requires: gh CLI authenticated with repo access.
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path


def print_rate_limit(label: str) -> None:
    """Print GitHub API rate limit status."""
    try:
        r = subprocess.run(
            ["gh", "api", "rate_limit"],
            capture_output=True,
            text=True,
        )
        if r.returncode != 0:
            return
        data = json.loads(r.stdout)
        core = data.get("resources", {}).get("core", {})
        graphql = data.get("resources", {}).get("graphql", {})
        print(
            f"[{label}] API limits —"
            f" REST: {core.get('remaining', '?')}"
            f"/{core.get('limit', '?')},"
            f" GraphQL: {graphql.get('remaining', '?')}"
            f"/{graphql.get('limit', '?')}"
        )
    except (FileNotFoundError, json.JSONDecodeError, KeyError):
        pass


def run_gh(args: list[str]) -> list[dict]:
    """Run gh CLI command, return parsed JSON."""
    try:
        r = subprocess.run(["gh"] + args, capture_output=True, text=True)
    except FileNotFoundError:
        print(
            "ERROR: gh CLI not found." " Install from https://cli.github.com/",
            file=sys.stderr,
        )
        sys.exit(1)
    if r.returncode != 0:
        print(
            f"ERROR: gh {' '.join(args[:4])}..." f" failed: {r.stderr.strip()}",
            file=sys.stderr,
        )
        return []
    try:
        return json.loads(r.stdout)
    except json.JSONDecodeError:
        print(
            f"ERROR: invalid JSON from gh" f" {' '.join(args[:4])}",
            file=sys.stderr,
        )
        return []


def count_main_merges(pr: dict) -> int:
    """Count commits that merge main into the PR branch.

    Detects GitHub "Update branch" button merges and manual
    ``git merge main`` / ``git merge origin/main`` commits.
    """
    count = 0
    for c in pr.get("commits", []):
        msg = c.get("messageHeadline", "")
        if msg.startswith("Merge branch 'main'") or msg.startswith(
            "Merge remote-tracking branch 'origin/main'"
        ):
            count += 1
    return count


def extract_reviewers(pr: dict) -> list[str]:
    """Extract unique reviewer logins from PR reviews."""
    reviewers: set[str] = set()
    for r in pr.get("reviews", []):
        login = r.get("author", {}).get("login", "")
        if login:
            reviewers.add(login)
    return sorted(reviewers)


def compact_merged(pr: dict, repo: str) -> dict:
    return {
        "additions": pr.get("additions", 0),
        "deletions": pr.get("deletions", 0),
        "author": {
            "is_bot": pr.get("author", {}).get("is_bot", False),
            "login": pr.get("author", {}).get("login", ""),
        },
        "baseRefName": pr.get("baseRefName", "main"),
        "createdAt": pr.get("createdAt", ""),
        "mergedAt": pr.get("mergedAt", ""),
        "number": pr.get("number", 0),
        "title": pr.get("title", "")[:50],
        "repo": repo,
        "mainMerges": count_main_merges(pr),
        "reviewers": extract_reviewers(pr),
    }


def compact_open(pr: dict, repo: str) -> dict:
    return {
        "n": pr.get("number", 0),
        "t": pr.get("title", "")[:40],
        "a": pr.get("author", {}).get("login", ""),
        "b": pr.get("baseRefName", "main"),
        "c": pr.get("createdAt", "")[:10],
        "l": pr.get("additions", 0) + pr.get("deletions", 0),
        "d": 1 if pr.get("isDraft") else 0,
        "r": repo,
    }


def compact_closed(pr: dict, repo: str) -> dict:
    return {
        "n": pr.get("number", 0),
        "t": pr.get("title", "")[:40],
        "a": pr.get("author", {}).get("login", ""),
        "c": pr.get("createdAt", "")[:10],
        "x": pr.get("closedAt", "")[:10],
        "l": pr.get("additions", 0) + pr.get("deletions", 0),
        "r": repo,
    }


def enrich_pr(repo: str, pr_number: int) -> dict:
    """Fetch commits and reviews for a single PR."""
    try:
        r = subprocess.run(
            [
                "gh",
                "pr",
                "view",
                str(pr_number),
                "--repo",
                repo,
                "--json",
                "commits,reviews",
            ],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return {"commits": [], "reviews": []}
    if r.returncode != 0:
        return {"commits": [], "reviews": []}
    try:
        return json.loads(r.stdout)
    except json.JSONDecodeError:
        return {"commits": [], "reviews": []}


def fetch_repo_data(
    repo: str,
    cutoff: str,
    fields_merged: str,
    fields_open: str,
    fields_closed: str,
) -> tuple[list[dict], list[dict], list[dict]]:
    """Fetch PR data for a single repo."""
    print(f"\n--- {repo} ---")

    print(f"  Fetching merged PRs since {cutoff}...")
    merged_raw = run_gh(
        [
            "pr",
            "list",
            "--repo",
            repo,
            "--state",
            "merged",
            "--json",
            fields_merged,
            "--limit",
            "500",
            "--search",
            f"merged:>{cutoff}",
        ]
    )
    human_merged = [p for p in merged_raw if not p.get("author", {}).get("is_bot")]
    print(f"    {len(human_merged)} merged PRs (human)")

    # Enrich each PR with commits/reviews individually
    # to avoid GraphQL node limit on bulk queries
    print(f"    Enriching {len(human_merged)} PRs" " with commit/review data...")
    for i, p in enumerate(human_merged):
        extra = enrich_pr(repo, p.get("number", 0))
        p["commits"] = extra.get("commits", [])
        p["reviews"] = extra.get("reviews", [])
        if (i + 1) % 50 == 0:
            print(f"      {i + 1}/{len(human_merged)}")

    merged = [compact_merged(p, repo) for p in human_merged]
    print(f"    {len(merged)} merged PRs enriched")

    print("  Fetching open PRs...")
    open_raw = run_gh(
        [
            "pr",
            "list",
            "--repo",
            repo,
            "--state",
            "open",
            "--json",
            fields_open,
            "--limit",
            "500",
        ]
    )
    opened = [
        compact_open(p, repo) for p in open_raw if not p.get("author", {}).get("is_bot")
    ]
    print(f"    {len(opened)} open PRs (human)")

    print(f"  Fetching closed (not merged) PRs" f" since {cutoff}...")
    closed_raw = run_gh(
        [
            "pr",
            "list",
            "--repo",
            repo,
            "--search",
            f"is:closed is:unmerged closed:>{cutoff}",
            "--json",
            fields_closed,
            "--limit",
            "200",
        ]
    )
    closed = [
        compact_closed(p, repo)
        for p in closed_raw
        if not p.get("author", {}).get("is_bot")
    ]
    print(f"    {len(closed)} closed (not merged) PRs")

    return merged, opened, closed


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Refresh velocity data")
    parser.add_argument(
        "--repo",
        dest="repos",
        action="append",
        required=True,
        help="GitHub repo in owner/repo format (repeatable)",
    )
    parser.add_argument("--days", type=int, default=42)
    parser.add_argument(
        "--open",
        action="store_true",
        help="Open dashboard in browser after generating",
    )
    parser.add_argument(
        "--output",
        default="output/dashboard.html",
        help="Output file path (default: output/dashboard.html)",
    )
    args = parser.parse_args()

    cutoff = (datetime.now() - timedelta(days=args.days)).strftime("%Y-%m-%d")
    fields_merged = (
        "number,title,author,createdAt,mergedAt,"
        "additions,deletions,baseRefName,headRefName"
    )
    fields_open = (
        "number,title,author,createdAt,baseRefName," "additions,deletions,isDraft"
    )
    fields_closed = (
        "number,title,author,createdAt,closedAt," "baseRefName,additions,deletions"
    )

    print_rate_limit("before")

    all_merged: list[dict] = []
    all_open: list[dict] = []
    all_closed: list[dict] = []

    for repo in args.repos:
        merged, opened, closed = fetch_repo_data(
            repo,
            cutoff,
            fields_merged,
            fields_open,
            fields_closed,
        )
        all_merged.extend(merged)
        all_open.extend(opened)
        all_closed.extend(closed)

    data: dict = {
        "repos": args.repos,
        "generated": datetime.now().strftime("%Y-%m-%dT%H:%M"),
        "days": args.days,
        "merged": all_merged,
        "open": all_open,
        "closed": all_closed,
    }

    data_json = json.dumps(data, separators=(",", ":"))

    # Read index.html template and inline the data
    template_path = Path(os.path.dirname(os.path.abspath(__file__))) / "index.html"
    try:
        template = template_path.read_text()
    except OSError as e:
        print(
            f"ERROR: Cannot read {template_path}: {e}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Replace fetch() call with inline data
    fetch_line = (
        "fetch('./data.json')"
        ".then(function(r){return r.json()})"
        ".then(function(raw){"
    )
    inline_line = "Promise.resolve(" + data_json + ").then(function(raw){"
    if fetch_line not in template:
        print(
            "ERROR: Cannot find fetch() line in" f" {template_path}",
            file=sys.stderr,
        )
        sys.exit(1)

    output_html = template.replace(fetch_line, inline_line)

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    try:
        with open(args.output, "w") as f:
            f.write(output_html)
    except OSError as e:
        print(
            f"ERROR: Failed to write {args.output}: {e}",
            file=sys.stderr,
        )
        sys.exit(1)

    print(
        f"\nWrote {args.output}"
        f" ({len(all_merged)} merged,"
        f" {len(all_open)} open,"
        f" {len(all_closed)} closed)"
    )

    print_rate_limit("after")

    if args.open:
        import webbrowser

        webbrowser.open(Path(args.output).resolve().as_uri())


if __name__ == "__main__":
    main()
